import { notFound } from "next/navigation";
import { Logo } from "@/components/brand";
import { ReportView } from "@/components/reports/report-view";
import { readStats } from "@/lib/data/reports";
import { createClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/env";

export const metadata = { title: "Weekly report", robots: { index: false, follow: false } };

type Shared = { week_start: string; stats: unknown; highlights: string; student_note: string; student_name: string; submitted_at: string };

/** Public, read-only view of one report the student chose to share. Nothing else is reachable from here. */
export default async function SharedReportPage({ params }: PageProps<"/r/[token]">) {
  const { token } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(token) || !isSupabaseConfigured()) notFound();

  const supabase = await createClient();
  const { data } = await supabase.rpc("get_shared_report", { p_token: token });
  const report = data as Shared | null;
  const stats = report ? readStats(report.stats) : null;
  if (!report || !stats) notFound();

  return (
    <div className="mx-auto max-w-3xl px-4 py-10">
      <header className="mb-6 flex items-center justify-between gap-3">
        <Logo className="text-sm" />
        <span className="text-xs text-muted-foreground">Shared weekly report · read-only</span>
      </header>
      <ReportView stats={stats} highlights={report.highlights} note={report.student_note} studentName={report.student_name} linkTasks={false} />
      <footer className="mt-10 border-t pt-4 text-xs text-muted-foreground">
        Generated by ResearchFlow from the student&apos;s daily logs and tasks, and frozen when submitted on{" "}
        {new Date(report.submitted_at).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" })}.
      </footer>
    </div>
  );
}
